# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'trifle' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for trifle
pod 'AFNetworking'
pod 'SDWebImage'
pod 'SnapKit'
pod 'SVProgressHUD'
pod 'MJRefresh'
end
